language: ruby
sudo: required
services:
- docker
rvm:
- 2.3
env:
- IMAGE=centos:7
- IMAGE=debian:jessie
bundler_args: "--jobs=4"
cache: bundler
before_install:
- gem update --system --no-document
- gem install bundler --no-document
script:
- bundle exec itamae docker --node-yaml=recipes/node.yml recipes/install.rb --image=$IMAGE --tag itamae-plugin:latest
- DOCKER_IMAGE=itamae-plugin:latest bundle exec rspec
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: Cp14VhyCUMUbQ/qvt1N96ZZUfJHQWq/car8TKVpO2vZ9DlajIIVuZrQ2HtekXTfnjiZ+8WI+ZShk2h78XLZk15CwdTx0RbGm8BSRv93nM9vsYoSUIkc1nFfCO7k3sfUA4JpK7aWz5KrqxsuHYnfLEtwVjuHys+JglyQ0aIu+eCYNNNIPVjXNsdz007tMdI8k7xCv4XeungICgn7b2+GPIes4MtdF069jUvAbzGWDm2vE86xE9N8rCCO+aqgaJVJaw2KxCxUlCQGbl4ewqGZy/8T1YScsYpSORSnpIu3aUbYz1ZG+NqGsLn4oL+NTNv5z/qIyEvpSaV/UtG6VsydPyOD9i2Db4mEtUFq1g3f/K3JBk2CQ4HFDzu227Fl9vo7Dn8DpMMDdAn61N5xAvjaT8L/6eQKkDSOm8v/zUR3P0frxB/SCDJceyE9whlODBeuZl/Y+63tPlVD/0wEb3ORiiHg6jyI881UpremtBzVWOPaN2oeTw0wEXxVy762j40jKW9Ka1Cnbk1d5qF8SxASOdBQ03Ud+bBy3z47sqp8fRrCUYc9np0yYi80kc2BwLrnAoEOaoFFnRTyQBSK82+BVkJtkpLNbzpBYG1sJxM2t5TF1VkdMsjkWgIuIc/EA8jKcVztY9565GWMM2zpY2q/2Lb1T/CUe/uQCxNC20ul5nVA=
