language: ruby
sudo: required
services:
  - docker
rvm:
  - 2.3
env:
  - IMAGE=centos:7
  - IMAGE=debian:jessie
bundler_args: "--jobs=4"
cache: bundler
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
script:
  - bundle exec itamae docker --node-yaml=recipes/node.yml recipes/install.rb --image=$IMAGE --tag itamae-plugin:latest
  - DOCKER_IMAGE=itamae-plugin:latest bundle exec rspec
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: SUgq+grsw1oaJL4W+OZFqX1AM07lLrk3eFkgS0TUO7rAW0OPzb/frXuF7otfCopOUu0RC+74Cg7JdeC29S1I+08fippGo15ZBSQ79I8GEILBgmIms1AWkncI8CqIUcEfO9SxqSc9Z9cuKp1TM3yIjU2iDkiVxw4pevb3vK73lXqRoXpDbB+S5a129Y7RjOo2lcncBCBWPe+1A87vGgEYVeRU1WtTR8N1BqOP8K3hG+BF0ZZM9e2u0jC5k8yJ5oi7MXEpldjJvv3lnBxyMDIOUGJ0N6Md1YM/anxRp9KDCZENNSucEDSLY14exLL1xeCy2fUPvK5zxiXYFIsCPmz+SjVby/VO6/LPpV8iVECy55b+XAQbZj+ZR9okxgvhzQr1JoxhuJgkXMRg1aP25+5JfV74ZEk6G9s7BgvkMvpJ6Gl9CDIm2/tQy9Ro9nNBg0VbXLno9njamkF7VjZODywTSGXNH7f4JtduxdDHmfLTtNPpj1eDIrXAqYsJu3vd/nTI65jquR9xNpz6QeRAX8xGDucnmtqEvu/ebHEq3x9AhuSn4bhXjElaBW7sFo0qdTMM1UkOe3DfSFz6t2Tku8UIttI57c5qO/FbyIcLAQmiHQCtDIqELF3q2yPXQ9Qz9jCmk2/0ENKD647TEcl2YWpyQpC590FyH8KFef5tgV6pTwM=
